<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class LeaseTenantStoreRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            // Lease
            'lease' => 'sometimes|array',
            'lease.entity_id' => 'nullable|exists:entities,id',
            'lease.property_id' => 'required_with:lease',
            'lease.property_type' => 'nullable|string|max:255',
            'lease.guarantor' => 'required_with:lease|string|max:255',
            'lease.lease_term_effective_dates.lease_type' => 'nullable|string|max:255',
            'lease.lease_term_effective_dates.furnished_lease_term_type' => 'nullable|string|max:255',
            'lease.lease_term_effective_dates.furnished_lease_duration' => 'nullable|integer|min:1',
            'lease.lease_term_effective_dates.unfurnished_lease_term_type' => 'nullable|string|max:255',
            'lease.lease_term_effective_dates.unfurnished_lease_duration' => 'nullable|integer|min:1',
            'lease.lease_term_effective_dates.commercial_lease_term_type' => 'nullable|string|max:255',
            'lease.lease_term_effective_dates.commercial_lease_duration' => 'nullable|integer|min:1',
            'lease.lease_term_effective_dates.professional_lease_term_type' => 'nullable|string|max:255',
            'lease.lease_term_effective_dates.professional_lease_duration' => 'nullable|integer|min:1',
            'lease.lease_term_effective_dates.lease_signing_date' => 'nullable|date',
            'lease.lease_term_effective_dates.lease_effective_date' => 'nullable|date|after_or_equal:lease.lease_term_effective_dates.lease_signing_date',
            'lease.lease_term_effective_dates.lease_renewal_conditions_type' => 'nullable|string',
            'lease.lease_term_effective_dates.other_lease_renewal_conditions' => 'nullable|string',
            'lease.lease_financial_rent_conditions.rent_amount' => 'nullable|numeric|min:0',
            'lease.lease_financial_rent_conditions.rent_payment_due_date' => 'nullable|date',
            'lease.lease_financial_rent_conditions.rent_payment_frequency' => 'nullable|string|max:255',
            'lease.lease_financial_rent_conditions.preferred_rent_payment_method' => 'nullable|string|max:255',
            'lease.lease_financial_rent_conditions.other_accepted_payment_methods' => 'nullable|string',
            'lease.lease_financial_service_charges_conditions.type_of_service_charges' => 'nullable|string|max:255',
            'lease.lease_financial_service_charges_conditions.monthly_flat_rate_amount' => 'nullable|numeric|min:0',
            'lease.lease_financial_service_charges_conditions.fixed_charges_included' => 'nullable|string',
            'lease.lease_financial_service_charges_conditions.monthly_provision_actual_charges' => 'nullable|numeric|min:0',
            'lease.lease_financial_service_charges_conditions.types_of_actual_charges' => 'nullable|string',
            'lease.lease_financial_service_charges_conditions.procedures_regularization_actual_charges' => 'nullable|string',
            'lease.lease_financial_service_charges_conditions.distribution_charges_co_tenants' => 'nullable|string',
            'lease.lease_financial_service_charges_conditions.property_tax_allocation' => 'nullable|string|max:255',
            'lease.lease_financial_service_charges_conditions.property_tax_allocation_other' => 'nullable|string',
            'lease.lease_financial_service_charges_conditions.co_ownership_charges_allocation' => 'nullable|string|max:255',
            'lease.lease_financial_service_charges_conditions.co_ownership_charges_allocation_other' => 'nullable|string',
            'lease.lease_financial_service_charges_conditions.insurance_allocation' => 'nullable|string|max:255',
            'lease.lease_financial_service_charges_conditions.insurance_allocation_other' => 'nullable|string',
            'lease.lease_financial_service_charges_conditions.maintenance_repairs_allocation' => 'nullable|string|max:255',
            'lease.lease_financial_service_charges_conditions.maintenance_repairs_allocation_other' => 'nullable|string',
            'lease.lease_financial_service_charges_conditions.taxes_fees_allocation' => 'nullable|string|max:255',
            'lease.lease_financial_service_charges_conditions.taxes_fees_allocation_other' => 'nullable|string',
            'lease.lease_financial_service_charges_conditions.amount_of_security_deposit' => 'nullable|numeric|min:0',
            'lease.lease_rent_revision_conditions.frequency_of_rent_revision' => 'nullable|string|max:255',
            'lease.lease_rent_revision_conditions.date_of_last_rent_revision' => 'nullable|date',
            'lease.lease_rent_revision_conditions.reference_index' => 'nullable|string|max:255',
            'lease.lease_rent_revision_conditions.other_index_to_specify' => 'nullable|string',
            'lease.lease_rent_revision_conditions.index_reference_quarter' => 'nullable|string|max:255',
            'lease.lease_rent_revision_conditions.index_reference_year' => 'nullable|string|max:255',
            'lease.lease_rent_revision_conditions.reference_index_value' => 'nullable|numeric|min:0',
            'lease.lease_rent_revision_conditions.revision_formula' => 'nullable|string',
            'lease.lease_specific_clauses.joint_several_liability_clause' => 'nullable|string',
            'lease.lease_specific_clauses.termination_clause' => 'nullable|string',
            'lease.lease_specific_clauses.termination_clause_grounds' => 'nullable|string',
            'lease.lease_specific_clauses.destination_clause_type_of_use' => 'nullable|string|max:255',
            'lease.lease_specific_clauses.key_money_right_to_lease' => 'nullable|string',
            'lease.lease_specific_clauses.key_money_amount' => 'nullable|numeric|min:0',
            'lease.lease_specific_clauses.key_money_legal_qualification' => 'nullable|string|max:255',
            'lease.lease_specific_clauses.right_to_lease_existence' => 'nullable|string',
            'lease.lease_specific_clauses.right_to_lease_conditions_assignment' => 'nullable|string',
            'lease.lease_specific_clauses.right_to_lease_value' => 'nullable|numeric|min:0',
            'lease.lease_documents.inventory_of_premises_annex' => 'nullable|string|max:255',
            'lease.lease_documents.technical_diagnostics_ddt_annex' => 'nullable|string|max:255',
            'lease.lease_documents.inventory_of_furnishings_annex' => 'nullable|string|max:255',
            'lease.lease_documents.co_ownership_regulations_annex' => 'nullable|string|max:255',
            'lease.lease_documents.landlord_bank_details_annex' => 'nullable|string|max:255',
            'lease.lease_documents.student_mobility_lease_justification_annex' => 'nullable|string|max:255',
            'lease.lease_documents.other_documents' => 'nullable|string',
            'lease.lease_zekeez_automations.generate_rents_from' => 'nullable|date',
            'lease.lease_zekeez_automations.has_tenant_balance' => 'nullable|boolean',
            'lease.lease_zekeez_automations.tenant_balance' => 'nullable|numeric|min:0',
            'lease.lease_zekeez_automations.automatic_rent_revision' => 'nullable|boolean',
            'lease.lease_zekeez_automations.automatic_rent_receipt_sending' => 'nullable|boolean',
            'lease.lease_zekeez_automations.automatic_rent_call_sending' => 'nullable|boolean',
            'lease.lease_zekeez_automations.rent_call_sending_date' => 'nullable|date',
            'lease.lease_zekeez_automations.automatic_first_reminder_unpaid_rent' => 'nullable|boolean',
            'lease.lease_zekeez_automations.first_unpaid_rent_reminder_sending_date' => 'nullable|date|after_or_equal:lease.lease_zekeez_automations.rent_call_sending_date',
            'lease.lease_zekeez_automations.automatic_second_reminder_unpaid_rent' => 'nullable|boolean',
            'lease.lease_zekeez_automations.second_unpaid_rent_reminder_sending_date' => 'nullable|date|after_or_equal:lease.lease_zekeez_automations.first_unpaid_rent_reminder_sending_date',
            'lease.lease_zekeez_automations.automatic_third_reminder_unpaid_rent' => 'nullable|boolean',
            'lease.lease_zekeez_automations.third_unpaid_rent_reminder_sending_date' => 'nullable|date|after_or_equal:lease.lease_zekeez_automations.second_unpaid_rent_reminder_sending_date',
            'lease.lease_end_details.departure_date_of_the_tenant' => 'nullable|date',
            'lease.lease_end_details.deposit_to_be_returned' => 'nullable|numeric|min:0',
            'lease.lease_end_details.date_of_return_of_the_security_deposit' => 'nullable|date|after_or_equal:lease.lease_end_details.departure_date_of_the_tenant',

            // Tenant
            'tenant' => 'sometimes|array',
            'tenant.lease_id' => 'nullable|exists:leases,id',
            'tenant.type' => 'required_with:tenant|in:individual,legal_entity',
            // 'tenant.property_id' => 'required_with:tenant',
            'tenant.entity_id' => 'nullable|exists:entities,id',
            'tenant.property_type' => 'nullable:tenant|string',
            'tenant.salutation' => 'nullable|string|max:255',
            'tenant.company_name' => 'nullable|string|max:255',
            'tenant.last_name' => 'required_with:tenant|string|max:255',
            'tenant.first_name' => 'required_with:tenant|string|max:255',
            'tenant.email' => 'required_with:tenant|email|max:255',
            'tenant.phone' => 'required_with:tenant|string|max:255',
            'tenant.date_of_birth' => 'required_with:tenant|date',
            'tenant.place_of_birth' => 'required_with:tenant|string|max:255',
            'tenant.address' => 'nullable|string',
            'tenant.additional_address' => 'nullable|string',
            'tenant.postal_code' => 'nullable|string|max:255',
            'tenant.city' => 'required_with:tenant|string|max:255',
            'tenant.country' => 'required_with:tenant|string|max:255',
            'tenant.owner_siret_siren_number' => 'nullable|string|max:255',
            'tenant.website' => 'nullable|string|max:255',
            'tenant.notes' => 'nullable|string',
            'tenant.representative_legal_entities.*.salutation' => 'nullable|string|max:255',
            'tenant.representative_legal_entities.*.name' => 'required_with:tenant.representative_legal_entities|string|max:255',
            'tenant.representative_legal_entities.*.first_name' => 'required_with:tenant.representative_legal_entities|string|max:255',
            'tenant.representative_legal_entities.*.quality' => 'required_with:tenant.representative_legal_entities|string|max:255',
            'tenant.representative_legal_entities.*.date_of_birth' => 'required_with:tenant.representative_legal_entities|date',
            'tenant.representative_legal_entities.*.place_of_birth' => 'required_with:tenant.representative_legal_entities|string|max:255',
            'tenant.representative_legal_entities.*.address' => 'nullable|string',
            'tenant.representative_legal_entities.*.additional_address' => 'nullable|string',
            'tenant.representative_legal_entities.*.postal_code' => 'nullable|string|max:255',
            'tenant.representative_legal_entities.*.city' => 'required_with:tenant.representative_legal_entities|string|max:255',
            'tenant.representative_legal_entities.*.country' => 'required_with:tenant.representative_legal_entities|string|max:255',
            'tenant.representative_legal_entities.*.phone' => 'required_with:tenant.representative_legal_entities|string|max:255',
            'tenant.bank_details.*.salutation' => 'nullable|string|max:255',
            'tenant.bank_details.*.name' => 'required_with:tenant.bank_details|string|max:255',
            'tenant.bank_details.*.first_name' => 'required_with:tenant.bank_details|string|max:255',
            'tenant.bank_details.*.quality' => 'required_with:tenant.bank_details|string|max:255',
            'tenant.bank_details.*.date_of_birth' => 'required_with:tenant.bank_details|date',
            'tenant.bank_details.*.place_of_birth' => 'required_with:tenant.bank_details|string|max:255',
            'tenant.bank_details.*.address' => 'nullable|string',
            'tenant.bank_details.*.additional_address' => 'nullable|string',
            'tenant.bank_details.*.postal_code' => 'nullable|string|max:255',
            'tenant.bank_details.*.city' => 'required_with:tenant.bank_details|string|max:255',
            'tenant.bank_details.*.country' => 'required_with:tenant.bank_details|string|max:255',
            'tenant.bank_details.*.phone' => 'required_with:tenant.bank_details|string|max:255',
        ];
    }
}