<?php

namespace App\Http\Requests;

use Illuminate\Validation\Rule;
use Illuminate\Foundation\Http\FormRequest;

class StorePropertyRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        // Debug the input data
        // dd($this->all());

        $rules = [
            // Building Rules (optional if building_id is provided)
            'building.entity_id' => 'nullable|exists:entities,id',
            'building.is_condominium' => 'nullable|boolean',
            'building.name' => 'nullable|string|max:255',
            'building.address' => 'nullable|string|max:2000',
            'building.post_code' => 'nullable|string|max:10',
            'building.city' => 'nullable|string|max:255',
            'building.country' => 'nullable|string|max:255',
            'building.construction_year' => 'nullable|integer|min:1800|max:' . date('Y'),

            // Building Facilities (optional)
            'building.building_facilities.entrance_hall' => 'nullable|string|max:255',
            'building.building_facilities.stairs' => 'nullable|string|max:255',
            'building.building_facilities.corridors' => 'nullable|string|max:255',
            'building.building_facilities.caretaker' => 'nullable|boolean',
            'building.building_facilities.elevator' => 'nullable|boolean',
            'building.building_facilities.elevator_access_condition' => 'nullable|string|max:255',
            'building.building_facilities.bicycle_storage' => 'nullable|boolean',
            'building.building_facilities.common_courtyard' => 'nullable|boolean',
            'building.building_facilities.common_garden' => 'nullable|boolean',
            'building.building_facilities.garbage_room' => 'nullable|boolean',
            'building.building_facilities.other_common_areas' => 'nullable|string|max:255',
            'building.building_facilities.intercom' => 'nullable|boolean',
            'building.building_facilities.digital_lock' => 'nullable|boolean',
            'building.building_facilities.collective_tv_antenna' => 'nullable|boolean',
            'building.building_facilities.childrens_playground' => 'nullable|boolean',
            'building.building_facilities.collective_green_spaces' => 'nullable|boolean',
            'building.building_facilities.parking' => 'nullable|boolean',
            'building.building_facilities.automated_access_gate' => 'nullable|boolean',
            'building.building_facilities.automated_access_gate_type' => 'nullable|string',
            'building.building_facilities.collective_outdoor_lighting' => 'nullable|boolean',
            'building.building_facilities.cellar' => 'nullable|boolean',
            'building.building_facilities.collective_alarm' => 'nullable|boolean',
            'building.building_facilities.electrical_charging_station_vehicle' => 'nullable|boolean',
            'building.building_facilities.common_tennis_court' => 'nullable|boolean',
            'building.building_facilities.collective_heating_with_individual_meter' => 'nullable|boolean',
            'building.building_facilities.collective_heating_without_individual_meter' => 'nullable|boolean',
            'building.building_facilities.condominium_regulations' => 'nullable|boolean',
            'building.building_facilities.video_surveillance_cameras' => 'nullable|boolean',
            'building.building_facilities.smoke_detection_system' => 'nullable|boolean',
            'building.building_facilities.collective_ventilation_system' => 'nullable|boolean',
            'building.building_facilities.collective_access_lighting' => 'nullable|boolean',
            'building.building_facilities.common_sanitary_facilities' => 'nullable|boolean',
            'building.building_facilities.fire_safety_system' => 'nullable|boolean',
            'building.building_facilities.service_elevator' => 'nullable|boolean',
            'building.building_facilities.common_swimming_pool' => 'nullable|boolean',
            'building.building_facilities.collective_heating' => 'nullable|boolean',
            'building.building_facilities.collective_hot_water' => 'nullable|boolean',
            'building.building_facilities.collective_hot_water_with_individual_meter' => 'nullable|boolean',
            'building.building_facilities.collective_hot_water_without_individual_meter' => 'nullable|boolean',
            'building.building_facilities.other_specific_collective_equipment' => 'nullable|boolean',

            // Unit Rules (optional if unit_id is provided)
            'unit.entity_id' => 'nullable|exists:entities,id',
            'unit.building_id' => 'nullable|exists:buildings,id', // Kept nullable
            'unit.unit_id' => 'nullable|exists:units,id',
            'unit.name' => 'nullable|string|max:255',
            'unit.type' => 'nullable|string|max:255',
            'unit.address' => 'nullable|string|max:2000',
            'unit.post_code' => 'nullable|string|max:10',
            'unit.city' => 'nullable|string|max:255',
            'unit.country' => 'nullable|string|max:255',
            'unit.tax_number' => 'nullable|string|max:20',
            'unit.dpe' => 'nullable|string|max:255',
            'unit.dpe_validity' => 'nullable|date',
            'unit.construction_year' => 'nullable|integer|min:1800|max:' . date('Y'),
            'unit.floor' => 'nullable|integer',
            'unit.lot_number' => 'nullable|string|max:255',
            'unit.cadastral_reference' => 'nullable|string|max:2000',

            // Unit Destination Premises
            'unit.unit_destination_premises.auth_com_act' => 'nullable|string',
            'unit.unit_destination_premises.proh_com_act' => 'nullable|string',
            'unit.unit_destination_premises.excl_clause' => 'nullable|boolean',
            'unit.unit_destination_premises.auth_lib_prof' => 'nullable|string',
            'unit.unit_destination_premises.proh_lib_prof' => 'nullable|string',
            'unit.unit_destination_premises.excl_clause_prof' => 'nullable|boolean',
            'unit.unit_destination_premises.auth_rel_act' => 'nullable|string',
            'unit.unit_destination_premises.excl_veh_park_type' => 'nullable|string',
            'unit.unit_destination_premises.proh_store' => 'nullable|boolean',
            'unit.unit_destination_premises.spec_use_lot' => 'nullable|string',
            'unit.unit_destination_premises.spec_proh_lot' => 'nullable|string',

            // Unit Other Facilities
            'unit.unit_other_facilities.individual_heating' => 'nullable|boolean',
            'unit.unit_other_facilities.individual_heating_type' => 'nullable|string',
            'unit.unit_other_facilities.individual_heating_radiators' => 'nullable|boolean',
            'unit.unit_other_facilities.individual_heating_radiators_type' => 'nullable|string',
            'unit.unit_other_facilities.number_of_radiators' => 'nullable|integer|min:0',
            'unit.unit_other_facilities.collective_heating' => 'nullable|boolean',
            'unit.unit_other_facilities.collective_heating_without_individual_meter' => 'nullable|boolean',
            'unit.unit_other_facilities.collective_heating_with_individual_meter' => 'nullable|boolean',
            'unit.unit_other_facilities.individual_hot_water' => 'nullable|boolean',
            'unit.unit_other_facilities.individual_hot_water_type' => 'nullable|string',
            'unit.unit_other_facilities.collective_hot_water' => 'nullable|boolean',
            'unit.unit_other_facilities.collective_hot_water_without_individual_meter' => 'nullable|boolean',
            'unit.unit_other_facilities.collective_hot_water_with_individual_meter' => 'nullable|boolean',
            'unit.unit_other_facilities.vmc_ventilation' => 'nullable|boolean',
            'unit.unit_other_facilities.vmc_type' => 'nullable|string',
            'unit.unit_other_facilities.telephone_connection' => 'nullable|boolean',
            'unit.unit_other_facilities.telephone_connection_active_line' => 'nullable|boolean',
            'unit.unit_other_facilities.fiber_internet_connection' => 'nullable|boolean',
            'unit.unit_other_facilities.television_connection_antenna_type' => 'nullable|string',
            'unit.unit_other_facilities.television_connection_number_of_tv_sockets' => 'nullable|integer|min:0',
            'unit.unit_other_facilities.individual_water_meter' => 'nullable|boolean',
            'unit.unit_other_facilities.individual_water_meter_meter_number' => 'nullable|string|max:255',
            'unit.unit_other_facilities.individual_electricity_meter' => 'nullable|boolean',
            'unit.unit_other_facilities.individual_electricity_meter_number' => 'nullable|string|max:255',
            'unit.unit_other_facilities.individual_gas_meter' => 'nullable|boolean',
            'unit.unit_other_facilities.individual_gas_meter_number' => 'nullable|string|max:255',

            // Unit Bathroom Facilities
            'unit.unit_bathroom_facilities.shower' => 'nullable|boolean',
            'unit.unit_bathroom_facilities.shower_type' => 'nullable|string',
            'unit.unit_bathroom_facilities.bathtub' => 'nullable|boolean',
            'unit.unit_bathroom_facilities.bathtub_type' => 'nullable|string',
            'unit.unit_bathroom_facilities.washbasin' => 'nullable|boolean',
            'unit.unit_bathroom_facilities.washbasin_type' => 'nullable|string',
            'unit.unit_bathroom_facilities.wc' => 'nullable|boolean',
            'unit.unit_bathroom_facilities.wc_type' => 'nullable|string',
            'unit.unit_bathroom_facilities.towel_dryers' => 'nullable|boolean',
            'unit.unit_bathroom_facilities.mirror' => 'nullable|boolean',
            'unit.unit_bathroom_facilities.bathroom_lighting' => 'nullable|boolean',
            'unit.unit_bathroom_facilities.washbasin_furniture' => 'nullable|boolean',
            'unit.unit_bathroom_facilities.cupboards' => 'nullable|boolean',

            // Unit Kitchen Facilities
            'unit.unit_kitchen_facilities.cuisine_type' => 'nullable|string',
            'unit.unit_kitchen_facilities.cooking_plates' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.cooking_plate_type' => 'nullable|string',
            'unit.unit_kitchen_facilities.number_of_burners' => 'nullable|integer|min:0',
            'unit.unit_kitchen_facilities.oven' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.oven_type' => 'nullable|string',
            'unit.unit_kitchen_facilities.fridge' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.refrigerator_type' => 'nullable|string',
            'unit.unit_kitchen_facilities.refrigerator_capacity' => 'nullable|string|max:255',
            'unit.unit_kitchen_facilities.freezer' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.extractor_hood' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.microwave' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.dishwasher' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.washing_machine' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.dryer' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.small_household_appliances' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.small_household_appliances_details' => 'nullable|string|max:255',
            'unit.unit_kitchen_facilities.high_cupboard' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.low_cupboard' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.work_plan' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.sink' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.num_of_basins' => 'nullable|boolean',
            'unit.unit_kitchen_facilities.sink_material' => 'nullable|string|max:255',
            'unit.unit_kitchen_facilities.kitchen_light' => 'nullable|boolean',

            // Unit Comfort Elements
            'unit.unit_comfort_elements.balcony' => 'nullable|boolean',
            'unit.unit_comfort_elements.balcony_surface' => 'nullable|string|max:255',
            'unit.unit_comfort_elements.balcony_exposure' => 'nullable|string|max:255',
            'unit.unit_comfort_elements.terrace' => 'nullable|boolean',
            'unit.unit_comfort_elements.terrace_surface' => 'nullable|string|max:255',
            'unit.unit_comfort_elements.terrace_exposure' => 'nullable|string|max:255',
            'unit.unit_comfort_elements.terrace_type' => 'nullable|string',
            'unit.unit_comfort_elements.private_garden' => 'nullable|boolean',
            'unit.unit_comfort_elements.private_garden_area' => 'nullable|string|max:255',
            'unit.unit_comfort_elements.private_garden_description' => 'nullable|string',
            'unit.unit_comfort_elements.private_celllar' => 'nullable|boolean',
            'unit.unit_comfort_elements.private_parking' => 'nullable|boolean',
            'unit.unit_comfort_elements.private_parking_location' => 'nullable|string|max:255',
            'unit.unit_comfort_elements.private_parking_level' => 'nullable|string|max:255',
            'unit.unit_comfort_elements.private_garage' => 'nullable|boolean',
            'unit.unit_comfort_elements.private_garage_location' => 'nullable|string|max:255',
            'unit.unit_comfort_elements.private_garage_level' => 'nullable|string|max:255',
            'unit.unit_comfort_elements.other_elements' => 'nullable|string',
            'unit.unit_comfort_elements.air_conditioning' => 'nullable|boolean',
            'unit.unit_comfort_elements.air_conditioning_type' => 'nullable|string',
            'unit.unit_comfort_elements.air_condition_mode' => 'nullable|string',
            'unit.unit_comfort_elements.alarm' => 'nullable|boolean',
            'unit.unit_comfort_elements.alarm_type' => 'nullable|string|max:255',
            'unit.unit_comfort_elements.alarm_remote_monitoring' => 'nullable|string|max:255',
            'unit.unit_comfort_elements.metal_curtains' => 'nullable|boolean',
            'unit.unit_comfort_elements.secure_showcase' => 'nullable|boolean',
            'unit.unit_comfort_elements.smoke_extraction' => 'nullable|boolean',
            'unit.unit_comfort_elements.pmr_access' => 'nullable|boolean',
            'unit.unit_comfort_elements.pmr_access_details' => 'nullable|string',
            'unit.unit_comfort_elements.other_specific_equipment' => 'nullable|string',
            'unit.unit_comfort_elements.specific_access_condition' => 'nullable|string',
            'unit.unit_comfort_elements.specific_use_condition' => 'nullable|string',

            // Unit Details
            'unit.unit_details.num_of_living_room' => 'nullable|integer|min:0',
            'unit.unit_details.num_of_bedroom' => 'nullable|integer|min:0',
            'unit.unit_details.num_of_bathroom' => 'nullable|integer|min:0',
            'unit.unit_details.num_of_toilet' => 'nullable|integer|min:0',
            'unit.unit_details.habitable_area' => 'nullable|string|max:255',
            'unit.unit_details.commercial_area' => 'nullable|string|max:255',
            'unit.unit_details.sales_area' => 'nullable|string|max:255',
            'unit.unit_details.storage_area' => 'nullable|integer|min:0',
            'unit.unit_details.office_space' => 'nullable|string|max:255',
            'unit.unit_details.reserve_area' => 'nullable|string|max:255',
            'unit.unit_details.sanitary_area' => 'nullable|string|max:255',
            'unit.unit_details.professional_surface' => 'nullable|string|max:255',
            'unit.unit_details.reception_area' => 'nullable|string|max:255',
            'unit.unit_details.waiting_room_area' => 'nullable|string|max:255',
            'unit.unit_details.consultation_area' => 'nullable|string|max:255',
            'unit.unit_details.parking_type' => 'nullable|string|max:255',
            'unit.unit_details.parking_lease_length' => 'nullable|string|max:255',
            'unit.unit_details.parking_lease_width' => 'nullable|string|max:255',
            'unit.unit_details.parking_lease_height' => 'nullable|string|max:255',
            'unit.unit_details.property_type' => 'nullable|string|max:255',
            'unit.unit_details.other_type_of_lot' => 'nullable|string|max:255',
        ];



        return $rules;
    }
}
